# Uncomment the next line to define a global platform for your project
# platform :ios, '10.0'

target 'weyoung' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!
   pod 'ReactiveCocoa', :git => 'https://github.com/zhao0/ReactiveCocoa.git', :tag => '2.5.2'
   pod 'AFNetworking'
   pod 'MJRefresh'
   pod 'MJExtension'
   pod 'RongCloudIM/IMLib'
   pod 'RongCloudIM/IMKit'
   pod 'NJKWebViewProgress'
   pod 'WebViewJavascriptBridge'
   pod 'YYWebImage'
   pod 'IQKeyboardManager'
   pod 'Masonry'
  # Pods for weyoung

  target 'weyoungTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'weyoungUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
