# Uncomment the next line to define a global platform for your project
# platform :ios, '10.0'

target 'weyoung' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!
   pod 'AFNetworking'
   pod 'SDWebImage'
   pod 'MJRefresh'
   pod 'MJExtension'
   pod 'RongCloudIM/IMLib'
   pod 'RongCloudIM/IMKit'

  # Pods for weyoung

  target 'weyoungTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'weyoungUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
